ACTION = 'action'
TIME = 'time'
USER = 'user'
ACCOUNT_NAME = 'account_name'

RESPONSE = 'response'
PRESENCE = 'presence'
MESSAGE = 'message'
SENDER = 'from'
DESTINATION = 'to'
MESSAGE_TEXT = 'mess_text'
ERROR = 'error'
EXIT = 'exit'

DEFAULT_IP_ADDRESS = '127.0.0.1'
DEFAULT_SERVER_IP_ADDRESS = ''
DEFAULT_PORT = 7777

MAX_CONNECTIONS = 5
MAX_PACKAGE_LENGTH = 1024

ENCODING = 'utf-8'

RESPONSE_200 = {RESPONSE: 200}
RESPONSE_400 = {
    RESPONSE: 400,
    ERROR: None
}
