ACTION = 'action'
TIME = 'time'
USER = 'user'
ACCOUNT_NAME = 'account_name'

RESPONSE = 'response'
PRESENCE = 'presence'
ERROR = 'error'

DEFAULT_IP_ADDRESS = '127.0.0.1'
DEFAULT_SERVER_IP_ADDRESS = ''
DEFAULT_PORT = 7777

MAX_CONNECTIONS = 5
MAX_PACKAGE_LENGTH = 1024

ENCODING = 'utf-8'
